### ISSUE TITLE
Different versions for playwright-java and playwright npm

### ISSUE THREAD

**Issue by danielFesenmeyer** [orange-buffalo/testcontainers-playwright#123]
On current master (and probably in latest releases), it seems like the playwright-java and npm versions don't match.

I'm asking because I've observed an issue similar to https://github.com/vitest-dev/vitest/issues/4173, only with the docker feature, **not** with the local feature.

Not sure whether that would be fixed by upgrading the npm version, but I guess it makes sense to keep this versions in sync whenever possible. WDYT?

**Comment by orange-buffalo** [comment]
We write [logs](https://github.com/orange-buffalo/testcontainers-playwright/blob/master/src/main/kotlin/io/orangebuffalo/testcontainers/playwright/PlaywrightContainer.kt) under `PlaywrightContainer` logger to identify the potential incompatibilities between the  `playwright-java` and JS version inside the Docker image. 

Can you please check if you anything like this:
* `Will use Playwright image XXX for version YYY found on classpath`
* `Playwright version in container (XXX) is not compatible with`

Generally yes, the JS version must be identical to Java version including minor version component (patch can differ), according to Playwright [docs](https://playwright.dev/docs/api/class-browsertype#browser-type-launch-server). That's the reason we print those diagnostic logs.

**Comment by danielFesenmeyer** [comment]
OK, the latter warning ("not compatible") does not occur in the logs, so versions are matching. (We currently have set log level to WARN for your packages, probably I'll change it to INFO.)

I got a bit confused by the fixed version (1.32) in package(-lock).json and noticed later on (after creating the issue) that the actually used version is configured in the docker build.

**Comment by orange-buffalo** [comment]
We've removed the version from package.json and added some comments to avoid confusion about the version used.
I think there is nothing else we can in this issue. Please let us know if you believe there is still some problem with our image and feel free to reopen.

**Comment by danielFesenmeyer** [comment]
Thanks for the clarifying PR and all your work on this nice project :+1:
