### ISSUE TITLE
Add license and contributing files

### ISSUE THREAD

**Issue by orange-buffalo** [orange-buffalo/testcontainers-playwright#13]
To improve transparency and easy contributions, we should provide additional docs.

**Comment by danielFesenmeyer** [comment]
I'd be interested in the license.

**Comment by orange-buffalo** [comment]
Thanks for the reminder, @danielFesenmeyer.  These docs are provided now as part of the repository.

**Comment by danielFesenmeyer** [comment]
Thanks a lot, @orange-buffalo :+1:
